[package]
name = "yj"
version = "0.7.12"
authors = ["Bruce Adams <bruce.adams@acm.org>"]

categories = ["command-line-utilities"]
description = "Command line tool that converts YAML to JSON"
edition = "2018"
homepage = "https://github.com/bruceadams/yj"
keywords = ["json", "yaml"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/bruceadams/yj"

[badges]
travis-ci = { repository = "bruceadams/yj" }

[dependencies]
failure = "0.1"
serde_json = "1.0"
serde_yaml = "0.8"

[dependencies.structopt]
features = ["wrap_help"]
version = "0.2"
